
package com.ibm.maximo.wsdl.mxiswochange;

import com.ibm.maximo.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MXISWOCHANGEPortType", targetNamespace = "http://www.ibm.com/maximo/wsdl/MXISWOCHANGE")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MXISWOCHANGEPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.ibm.maximo.QueryMXISWOCHANGEResponseType
     */
    @WebMethod(operationName = "QueryMXISWOCHANGE", action = "urn:processDocument")
    @WebResult(name = "QueryMXISWOCHANGEResponse", targetNamespace = "http://www.ibm.com/maximo", partName = "parameters")
    public QueryMXISWOCHANGEResponseType queryMXISWOCHANGE(
        @WebParam(name = "QueryMXISWOCHANGE", targetNamespace = "http://www.ibm.com/maximo", partName = "parameters")
        QueryMXISWOCHANGEType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ibm.maximo.SyncMXISWOCHANGEResponseType
     */
    @WebMethod(operationName = "SyncMXISWOCHANGE", action = "urn:processDocument")
    @WebResult(name = "SyncMXISWOCHANGEResponse", targetNamespace = "http://www.ibm.com/maximo", partName = "parameters")
    public SyncMXISWOCHANGEResponseType syncMXISWOCHANGE(
        @WebParam(name = "SyncMXISWOCHANGE", targetNamespace = "http://www.ibm.com/maximo", partName = "parameters")
        SyncMXISWOCHANGEType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ibm.maximo.UpdateMXISWOCHANGEResponseType
     */
    @WebMethod(operationName = "UpdateMXISWOCHANGE", action = "urn:processDocument")
    @WebResult(name = "UpdateMXISWOCHANGEResponse", targetNamespace = "http://www.ibm.com/maximo", partName = "parameters")
    public UpdateMXISWOCHANGEResponseType updateMXISWOCHANGE(
        @WebParam(name = "UpdateMXISWOCHANGE", targetNamespace = "http://www.ibm.com/maximo", partName = "parameters")
        UpdateMXISWOCHANGEType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ibm.maximo.CreateMXISWOCHANGEResponseType
     */
    @WebMethod(operationName = "CreateMXISWOCHANGE", action = "urn:processDocument")
    @WebResult(name = "CreateMXISWOCHANGEResponse", targetNamespace = "http://www.ibm.com/maximo", partName = "parameters")
    public CreateMXISWOCHANGEResponseType createMXISWOCHANGE(
        @WebParam(name = "CreateMXISWOCHANGE", targetNamespace = "http://www.ibm.com/maximo", partName = "parameters")
        CreateMXISWOCHANGEType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns com.ibm.maximo.DeleteMXISWOCHANGEResponseType
     */
    @WebMethod(operationName = "DeleteMXISWOCHANGE", action = "urn:processDocument")
    @WebResult(name = "DeleteMXISWOCHANGEResponse", targetNamespace = "http://www.ibm.com/maximo", partName = "parameters")
    public DeleteMXISWOCHANGEResponseType deleteMXISWOCHANGE(
        @WebParam(name = "DeleteMXISWOCHANGE", targetNamespace = "http://www.ibm.com/maximo", partName = "parameters")
        DeleteMXISWOCHANGEType parameters);

}
