
package com.ibm.maximo.wsdl.mxiswochange;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MXISWOCHANGE", targetNamespace = "http://www.ibm.com/maximo/wsdl/MXISWOCHANGE", wsdlLocation = "file:/C:/Downloads/maximo/esls1uat.eu.smi.ibm.com_meaweb_wsdl_MXISWOCHANGE.wsdl")
public class MXISWOCHANGE
    extends Service
{

    private final static URL MXISWOCHANGE_WSDL_LOCATION;
    private final static WebServiceException MXISWOCHANGE_EXCEPTION;
    private final static QName MXISWOCHANGE_QNAME = new QName("http://www.ibm.com/maximo/wsdl/MXISWOCHANGE", "MXISWOCHANGE");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:maximo/esls1uat.eu.smi.ibm.com_meaweb_wsdl_MXISWOCHANGE.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MXISWOCHANGE_WSDL_LOCATION = url;
        MXISWOCHANGE_EXCEPTION = e;
    }

    public MXISWOCHANGE() {
        super(__getWsdlLocation(), MXISWOCHANGE_QNAME);
    }

    public MXISWOCHANGE(WebServiceFeature... features) {
        super(__getWsdlLocation(), MXISWOCHANGE_QNAME, features);
    }

    public MXISWOCHANGE(URL wsdlLocation) {
        super(wsdlLocation, MXISWOCHANGE_QNAME);
    }

    public MXISWOCHANGE(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MXISWOCHANGE_QNAME, features);
    }

    public MXISWOCHANGE(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MXISWOCHANGE(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MXISWOCHANGEPortType
     */
    @WebEndpoint(name = "MXISWOCHANGESOAP11Port")
    public MXISWOCHANGEPortType getMXISWOCHANGESOAP11Port() {
        return super.getPort(new QName("http://www.ibm.com/maximo/wsdl/MXISWOCHANGE", "MXISWOCHANGESOAP11Port"), MXISWOCHANGEPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MXISWOCHANGEPortType
     */
    @WebEndpoint(name = "MXISWOCHANGESOAP11Port")
    public MXISWOCHANGEPortType getMXISWOCHANGESOAP11Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ibm.com/maximo/wsdl/MXISWOCHANGE", "MXISWOCHANGESOAP11Port"), MXISWOCHANGEPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MXISWOCHANGE_EXCEPTION!= null) {
            throw MXISWOCHANGE_EXCEPTION;
        }
        return MXISWOCHANGE_WSDL_LOCATION;
    }

}
