//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.10 at 03:05:57 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ibm.com/maximo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.shopdirect.maximoautomation.infrastructure.maximo.ws;
